### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by rasmusagren** [Phynix/yamlloader#11]
Thanks for a nice improvement! Could you please add this to conda-forge? It's fast and easy. Thanks!

**Comment by rasmusagren** [comment]
I needed it, so I added it here https://github.com/conda-forge/staged-recipes/pull/5810.

**Comment by mayou36** [comment]
@rasmusagren okay, then thanks for that! I wanted to tackle it this week, but that's even better.

**Comment by mayou36** [comment]
@rasmusagren so one question keeps bothering me: why exactly did you need it fast (and not just use the `-c Phynix` flag) ? I am just wondering about the use case ;)

**Comment by rasmusagren** [comment]
It was a dependency for a larger workflow that is distributed as a conda-package. For testing, building and distributing that package it's much more convenient if all packages are on bioconda or conda-forge. Then I forgot about the last edits requested by conda-forge so it hasn't been merged yet anyways :) Maybe you could add the licence they ask for?

**Comment by mayou36** [comment]
Ah I see, yes that's of course easier.

The LICENSE file is there already, they requested to add the _field_ `license_file` to specify which is the LICENSE file. As it is your branch and I cannot edit it, I would ask you to add that field, ok?

(Btw: if you use someones name as in the conda-forge merge, just add the @ in front of it, so the person get's directly notified to be mentioned)
