### ISSUE TITLE
Keep Python 3.6 happy with UTF-8 encoded README.rst

### ISSUE THREAD

**Issue by mcepl** [Phynix/yamlloader#16]
Python 3.6 tries to open README.rst as ASCII encoded file and it fails spectacularly.

[This patch](https://github.com/Phynix/yamlloader/files/3939431/happy_utf8.patch.txt) makes UTF-8 encoding explicit.

**Comment by mayou36** [comment]
Where does it fail? And better do not provide patches as text files like this...

**Comment by mcepl** [comment]
Sorry, for trying to help you. Obviously, when you try to download file with a string ``François Ménabé`` as US-ASCII, everything works peachy. And no, I have hundreds of packages to maintain, so I cannot fork properly each of them. If my help is not nicely enough packaged for you, tough luck.

**Comment by mayou36** [comment]
Hi, I appreciate your help a lot, I was not aware of this issue!

to package it as a downloadable file makes every half-aware coder think that it is spam and contains a virus, better link to a github gist or just copy-paste it.

**Comment by mcepl** [comment]
OK, this is so simple that probably pasted-in patch would be a good idea.
