### ISSUE TITLE
Should always return an OrderedDict even for Python 3.7+

### ISSUE THREAD

**Issue by aszilagyi** [Phynix/yamlloader#17]
The ordereddict loader checks for Python version and if it is 3.7+ then returns a dict instead of an OrderedDict. This is not good as OrderedDict has an extra feature, namely the move_to_end method. Programs using this method will be broken. Also, PyYAML already returns a dict so if yamlloader.ordereddict also returns a dict then it is not needed.
The ordereddict loader should always return an OrderedDict regardless of Python version.

**Comment by redsk** [comment]
Setting `yamlloader.settings.PY_LE_36 = True` before loading it does the trick

**Comment by mayou36** [comment]
Hm, indeed, there is no downside to it I think

**Comment by mayou36** [comment]
Done and released with 1.0.0 Feel free to close

**Comment by aszilagyi** [comment]
Thank you! Closing.
