### ISSUE TITLE
Installing yamlloader 1.1.0 on Python 2.7/3.4 on Ubuntu

### ISSUE THREAD

**Issue by andy-maier** [Phynix/yamlloader#23]
Since the release of yamlloader 1.1.0, we are encountering the following issue, where an installation of a package that uses yamlloader, with the install command "setup.py {package} install" attempts to install yamlloader 1.1.0 on Python 2.7. Which obviously fails since yamlloader 1.1.0 somewhere uses a feature available only in python 3.6 and higher.

I tried to understand why it attempts to do that, but gave up. Our circumvention is to pin yamlloader to <1.0.0 on py<3.6.

The "install_requires" parameter of setup() inside of the setup.py script of our project specifies "yamlloader>=0.5.5".

Before the release of yamlloader 1.1.0, this install command successfully installed yamlloader 0.5.5 on python<3.6 as expected, i.e. it correctly ignored yamlloader 1.0.0 on these python versions.

Since the release of yamlloader 1.1.0, this install command attempts to install yamlloader 1.1.0 on python 2.7 and 3.4 on Ubuntu (I did not try python 3.5). On macos and windows on python 2.7, it behaves correctly and ignores 1.1.0 (I did not test with python 3.4 or 3.5 on these OSs). So the behavior depends on the OS.

I analyzed and compared the package metadata of the yamlloader 0.5.5, 1.0.0 and 1.1.0 packages on Pypi for both the source tarball and the wheel archive, and they all looked good to me (except for the snag with the __version__ attribute saying 0.5.5 in package version 1.0.0, but that attribute is not evaluated during the install, to my knowledge). The required Python version is always declared correctly in the PKG-INFO file of the source tarball as well as in the METADATA file of the wheel archive, with a Requires-Python" statement, and it is also correctly shown in the GUI of Pypi.

I have compared the versions of packages that are relevant for the installation for Python 2.7 on Ubuntu and macOS, such as pip, wheel, setuptools, and they were all the same versions. The Python version itself is 2.7.17 on Ubuntu and 2.7.18 on macOS, so there is a chance that something got fixed in Python. However, that does not really explain why yamlloader 1.0.0 gets successfully avoided. By the way, specifying "yamlloader>=0.5.5,<1.1.0" succeeds on ubuntu with Python 2.7. So 1.0.0 is reliably ignored as it should be. Just not 1.1.0.

I don't think that you can do anything about this, but I wanted to let you and other users know of the problem and how to circumvent it. Maybe someone understands what is going on there.

Link to the test runs that exhibit this behavior: https://github.com/pywbem/pywbem/actions/runs/1027402057.

**Comment by mayou36** [comment]
That is weird.... It installs fine in the CI with different versions.
Maybe it's a command problem, using pip instead of pip3?

**Comment by andy-maier** [comment]
Yes, it is weird.
The error happens on Python 2.7, and this is in our install tests where we verify different ways to install the package. The error happens not when we use pip to install, but when we use "python setup.py install".

From the test run linked above (the list of packages shown below is the complete list of packages in the virtual env at the time just before the setup.py script runs):
```
Creating virtualenv: tests/installtest/../../tmp_installtest/virtualenvs/pywbem_test_test2
Activating virtualenv: tests/installtest/../../tmp_installtest/virtualenvs/pywbem_test_test2
Virtualenv before reinstalling base packages:
Python version: Python 2.7.18 from /home/runner/work/pywbem/pywbem/tmp_installtest/virtualenvs/pywbem_test_test2/bin/python
Pip version: pip 20.3.4 from /home/runner/work/pywbem/pywbem/tmp_installtest/virtualenvs/pywbem_test_test2/lib/python2.7/site-packages/pip (python 2.7)
Debug: pip_version='20.3.4'
Reinstalling pip with PACKAGE_LEVEL=latest
Reinstalling setuptools with PACKAGE_LEVEL=latest
Reinstalling wheel with PACKAGE_LEVEL=latest
Virtualenv before actual install test:
Pip version: pip 20.3.4 from /home/runner/work/pywbem/pywbem/tmp_installtest/virtualenvs/pywbem_test_test2/lib/python2.7/site-packages/pip (python 2.7)
Packages:
Package    Version
---------- -------
pip        20.3.4
setuptools 44.1.1
wheel      0.36.2
Installing with setup.py from repo root directory (latest package levels)
### That's where it executes "python setup.py install" ...
Error: Command failed with rc=1: cd tests/installtest/../..; python setup.py install, output follows:
```

**Comment by jonas-eschle** [comment]
Sorry, this got under my radar! Yes, overall yamlloader moved forward to leave Python 2.7 behind as it was officially discontinued. May I ask what exactly would this be used for?

**Comment by jonas-eschle** [comment]
Checking the status, is there still need for this?
