### ISSUE TITLE
yamlloader release for Python 2.7 that rolls back the fix for relative imports

### ISSUE THREAD

**Issue by andy-maier** [Phynix/yamlloader#24]
Our package is part pf the RHEL distro, and they still support Python 2.7. Therefore, we are also still supporting it.

yamlloader 0.5.5 was the last version supporting Python 2.7, and it worked great for us until we began vendorizing it, at which point we ran into issue #20, which got fixed by PR #21.

Could we please have a yamlloader version 0.5.6 (or so) released that contains the rolled back fix from PR #21?

**Comment by andy-maier** [comment]
BTW, the old yamlordereddict package is in Fedora but its package maintainer in Fedora apparently does not want to migrate to using your yamlloader version. So in case you're interested in seeing your package in Fedora, there is possibly an opportunity there. See this comment here: https://github.com/pywbem/pywbem/issues/2434#issuecomment-878334349. Let me know if you're interested.

**Comment by mayou36** [comment]
Thanks for bringing this up! I asked in the thread to get an idea of why that does not work.

On the 2.7, I am very much not a friend of 2.7 after the end-of-lifetime, it's a cancer still around, but I am aware of the realities in the software world. So I guess this is doable, sure, I should be able to do that (may takes about two weeks as I am on vacation).

(otherwise feel free to cherrypick and PR, I can merge PRs with my phone but not really do a backport)

**Comment by andy-maier** [comment]
Thanks for the offer!

What is needed for me to create a PR on top of 0.5.5 is that it has a branch I can choose as the target of the PR. The commit of version 0.5.5 has a tag "0.5.5" but no branch at the moment.

I found out that it is possible to create a branch on top of a tagged commit via the GUI as follows. Probably requires switching to desktop mode on the phone...

- Go to main repo page ("Code")
- In the drop down for the branch, select the 0.5.5 tag
- Once it shows that tag, click again on the drop down, and this time type the name of the new branch in the search field (e.g. "fix_0.5". Click the button that now appears for creating the branch.

**Comment by jonas-eschle** [comment]
Hi, sorry this got lost, is this still an issue? Is Python 2.7 still supported by RHEL?
