### ISSUE TITLE
tests dependency on pytest

### ISSUE THREAD

**Issue by stanislavlevin** [Phynix/yamlloader#56]
`pytest` is marked as tests dependency but it's not used anywhere.

https://github.com/Phynix/yamlloader/blob/main/ci/run_tests.sh#L3

> coverage run  --source=. --branch -m unittest discover && coverage report src/yamlloader/*.py

**Comment by jonas-eschle** [comment]
You're right, thanks, fixing that

**Comment by jonas-eschle** [comment]
Resolved in #57
